### ISSUE TITLE
program within dataloader

### ISSUE THREAD

**Issue by gaopeng-eugene** [facebookresearch/clevr-iep#12]
python3.5 scripts/train_model.py   --model_type PG   --num_train_samples 18000   --num_iterations 20000   --checkpoint_every 1000   --checkpoint_path data/program_generator.pt
> /opt/data/penggao/pytorch_project/clevr-iep/clevr-iep/scripts/train_model.py(27)<module>()
-> import iep.utils as utils
(Pdb) c
Reading features from  data/train_features.h5
Reading questions from  data/train_questions.h5
Reading question data into memory
Reading features from  data/val_features.h5
Reading questions from  data/val_questions.h5
Reading question data into memory

Here is the program generator:
Seq2Seq (
  (encoder_embed): Embedding(93, 300)
  (encoder_rnn): LSTM(300, 256, num_layers=2, batch_first=True)
  (decoder_embed): Embedding(44, 300)
  (decoder_rnn): LSTM(556, 256, num_layers=2, batch_first=True)
  (decoder_linear): Linear (256 -> 44)
)
train_loader has 18000 samples
val_loader has 10000 samples
Starting epoch 1

Traceback (most recent call last):
  File "scripts/train_model.py", line 27, in <module>
    import iep.utils as utils
  File "scripts/train_model.py", line 154, in main
    train_loop(args, train_loader, val_loader)
  File "scripts/train_model.py", line 211, in train_loop
    for batch in train_loader:
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py", line 206, in __next__
    idx, batch = self.data_queue.get()
  File "/usr/lib/python3.5/multiprocessing/queues.py", line 345, in get
    return ForkingPickler.loads(res)
  File "/usr/local/lib/python3.5/dist-packages/torch/multiprocessing/reductions.py", line 70, in rebuild_storage_fd
    fd = df.detach()
  File "/usr/lib/python3.5/multiprocessing/resource_sharer.py", line 57, in detach
    with _resource_sharer.get_connection(self._id) as conn:
  File "/usr/lib/python3.5/multiprocessing/resource_sharer.py", line 87, in get_connection
    c = Client(address, authkey=process.current_process().authkey)
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 493, in Client
    answer_challenge(c, authkey)
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 732, in answer_challenge
    message = connection.recv_bytes(256)         # reject large message
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError

**Comment by gaopeng-eugene** [comment]
Can you help me solve this problem?

**Comment by gaopeng-eugene** [comment]
No on run into this problem?

**Comment by gaopeng-eugene** [comment]
No one run into this problem?

**Comment by kkjh0723** [comment]
@gaopeng-eugene I also got the same error message with baseline model. Did you solve the problem?

**Comment by rshivansh** [comment]
@gaopeng-eugene I got the same issue . How did u solve it ?
