### ISSUE TITLE
Error running baseline models

### ISSUE THREAD

**Issue by olivernina** [facebookresearch/clevr-iep#14]
Hi, first of all great work on this paper. Looking forward to see it at ICCV. 
I have an issue trying to run the baseline models such as CNN+LSTM and LSTM. I get the following error. Have you seen this problem before? It seems it always stops at that iteration. I also saw the error when running all the other baseline methods. Thanks for your help.

6721 0.31234210729599
6722 0.2944237291812897
6723 0.23815006017684937
Traceback (most recent call last):
  File "scripts/train_model.py", line 514, in <module>
    main(args)
  File "scripts/train_model.py", line 160, in main
    train_loop(args, train_loader, val_loader)
  File "scripts/train_model.py", line 246, in train_loop
    baseline_optimizer.step()
  File "/home/oliver/.local/lib/python3.5/site-packages/torch/optim/adam.py", line 70, in step
    bias_correction1 = 1 - beta1 ** state['step']
OverflowError: (34, 'Numerical result out of range')

**Comment by olivernina** [comment]
I actually was able to run the code in a different machine fine. This appears to be a hardware issue. Maybe there is a work around you can suggest. Thanks
