### ISSUE TITLE
pytorch 0.2.0 version compatibility

### ISSUE THREAD

**Issue by gaopeng-eugene** [facebookresearch/clevr-iep#15]
With the update of pytorch, the current code may run into error during inference and training. Here I will show the bugs and how to change the code.

**Comment by gaopeng-eugene** [comment]
when I run the demo code, I run into the following error.
/opt/data/penggao/pytorch_project/clevr-iep# python3 run_model.py   --program_generator models/CLEVR/program_generator_18k.pt   --execution_engine models/CLEVR/execution_engine_18k.pt   --image img/CLEVR_val_000013.png   --question "Does the small sphere have the same color as the cube left of the gray cube?"

Loading program generator from  models/CLEVR/program_generator_18k.pt
Loading execution engine from  models/CLEVR/execution_engine_18k.pt

Loading CNN for feature extraction
Running the model

Traceback (most recent call last):
  File "run_model.py", line 301, in <module>
    main(args)
  File "run_model.py", line 85, in main
    run_single_example(args, model)
  File "run_model.py", line 159, in run_single_example
    argmax=(args.sample_argmax == 1))
  File "/opt/data/penggao/pytorch_project/clevr-iep/iep/models/seq2seq.py", line 170, in reinforce_sample
    logprobs, h, c = self.decoder(encoded, cur_input, h0=h, c0=c)
  File "/opt/data/penggao/pytorch_project/clevr-iep/iep/models/seq2seq.py", line 92, in decoder
    V_in, V_out, D, H, L, N, T_in, T_out = self.get_dims(y=y)
  File "/opt/data/penggao/pytorch_project/clevr-iep/iep/models/seq2seq.py", line 57, in get_dims
    T_out = y.size(1) if y is not None else None
RuntimeError: invalid argument 2: out of range at /pytorch/torch/lib/THC/generic/THCTensor.c:23

**Comment by gaopeng-eugene** [comment]
change seq2seq model line 173
      if argmax:
        _, cur_output = probs.max(1)
      else:

to
      if argmax:
        _, cur_output = probs.max(1)
        cur_output = cur_output.unsqueeze(0)
      else:
