### ISSUE TITLE
RuntimeError of 'T_out = y.size(1) if y is not None else None'

### ISSUE THREAD

**Issue by cqqqqqqwang** [facebookresearch/clevr-iep#17]
Hi there, when I ran the scripts as instructed, I got the RuntimeError. Below are the details:
```
(PYENV) --- files/clevr-iep ‹master* M?› » python scripts/run_model.py \                                        1 ↵
  --program_generator models/CLEVR/program_generator_18k.pt \
  --execution_engine models/CLEVR/execution_engine_18k.pt \
  --image img/CLEVR_val_000013.png \
  --question "Does the small sphere have the same color as the cube left of the gray cube?"

Loading program generator from  models/CLEVR/program_generator_18k.pt
Loading execution engine from  models/CLEVR/execution_engine_18k.pt
Loading CNN for feature extraction
Running the model

y is: None
y is: Variable containing:
 1
[torch.cuda.LongTensor of size 1x1 (GPU 0)]

y is: Variable containing:
 5
[torch.cuda.LongTensor of size 1 (GPU 0)]

Traceback (most recent call last):
  File "scripts/run_model.py", line 301, in <module>
    main(args)
  File "scripts/run_model.py", line 85, in main
    run_single_example(args, model)
  File "scripts/run_model.py", line 159, in run_single_example
    argmax=(args.sample_argmax == 1))
  File "/u/home/downloads/files/clevr-iep/iep/models/seq2seq.py", line 171, in reinforce_sample
    logprobs, h, c = self.decoder(encoded, cur_input, h0=h, c0=c)
  File "/u/home/downloads/files/clevr-iep/iep/models/seq2seq.py", line 93, in decoder
    V_in, V_out, D, H, L, N, T_in, T_out = self.get_dims(y=y)
  File "/u/home/downloads/files/clevr-iep/iep/models/seq2seq.py", line 58, in get_dims
    T_out = y.size(1) if y is not None else None
RuntimeError: invalid argument 2: out of range at /opt/conda/conda-bld/pytorch_1502009910772/work/torch/lib/THC/generic/THCTensor.c:23
```

My python is of version 3.6, and the latest pytorch is installed.
I have printed the content of y, and it can be None, 1-by-1 torch.cuda.LongTensor, and 1 torch.cuda.LongTensor. So, when the size is 1, T_out = y.size(1) will lead to the RuntimeError.

**Comment by manoja328** [comment]
change seq2seq model line 173
if argmax:
_, cur_output = probs.max(1)
else:

to
if argmax:
_, cur_output = probs.max(1)
cur_output = cur_output.unsqueeze(0)
else:

**Comment by olivernina** [comment]
that worked for me thanks manoja328

**Comment by Victoria2333** [comment]
@manoja328,do you know how to compute test accuracy?coz there is no test answer in dataset,i don't know how to do it,and thanks very much~~~

**Comment by manoja328** [comment]
Hi,
Its in the file
https://github.com/facebookresearch/clevr-iep/blob/master/scripts/run_model.py
 in line 276 .. The preds variable is the answers.

_, preds = scores.data.cpu().max(1)
all_programs.append(programs_pred.data.cpu().clone())
all_scores.append(scores.data.cpu().clone())
all_probs.append(probs.data.cpu().clone())

.........

Best,
Manoj

**Comment by manoja328** [comment]
Hi,
Its in the file https://github.com/facebookresearch/clevr-iep/
blob/master/scripts/run_model.py  in line 276 .. The preds variable is the
answers.

_, preds = scores.data.cpu().max(1)
all_programs.append(programs_pred.data.cpu().clone())
all_scores.append(scores.data.cpu().clone())
all_probs.append(probs.data.cpu().clone())

.........

Best,
Manoj

**Comment by suddu22** [comment]
Hi
Use the code in the repo with no modification. Setup the environment as given in the readme.
Just make sure that your torch version is the one specified in the requirements.txt, your torchvision version is 0.1.9 and your python version is 3.5.2.
Hope it helps.
