### ISSUE TITLE
Error while running baseline model

### ISSUE THREAD

**Issue by kkjh0723** [facebookresearch/clevr-iep#19]
When I run baseline model in pytorch 0.2.0, I got following error,

    train_loader has 699989 samples
    val_loader has 10000 samples
    Starting epoch 1
    Traceback (most recent call last):
      File "scripts/train_model.py", line 491, in <module>
        main(args)
      File "scripts/train_model.py", line 152, in main
        train_loop(args, train_loader, val_loader)
      File "scripts/train_model.py", line 235, in train_loop
        scores = baseline_model(questions_var, feats_var)
      File "/root/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 224, in __call__
        result = self.forward(*input, **kwargs)
      File "/home/sharedfolder/clevr/clevr-iep/iep/models/baselines.py", line 242, in forward
        u = sa(v, u)
      File "/root/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 224, in __call__
        result = self.forward(*input, **kwargs)
      File "/home/sharedfolder/clevr/clevr-iep/iep/models/baselines.py", line 45, in forward
        v_tilde = (p.expand_as(v) * v).sum(2).sum(3).view(N, D)
      File "/root/anaconda3/lib/python3.6/site-packages/torch/autograd/variable.py", line 476, in sum
        return Sum.apply(self, dim, keepdim)
      File "/root/anaconda3/lib/python3.6/site-packages/torch/autograd/_functions/reduce.py", line 21, in forward
        return input.sum(dim)
    RuntimeError: dimension out of range (expected to be in range of [-3, 2], but got 3)

how can I fix this?

**Comment by jivatneet** [comment]
In the latest torch version, the sum dimensions are reduced. Making this change should work:
```
v_tilde = (p.expand_as(v) * v).sum(2, keepdim=True).sum(3, keepdim=True).view(N, D)

```
