### ISSUE TITLE
NoneType

### ISSUE THREAD

**Issue by lololun** [facebookresearch/clevr-iep#33]
我下载完数据之后在运行第二步提取图像特征时出现了内存溢出问题，我把图片缩减为20张之后出现下面这个错误，有谁可以帮我说一下怎么解决吗？ 谢谢
python scripts/extract_features.py   --input_image_dir data/CLEVR_v1.0/images/train   --output_h5_file data/train_features.h5

('data/CLEVR_v1.0/images/train/CLEVR_train_000000.png', 0)
('data/CLEVR_v1.0/images/train/CLEVR_train_000019.png', 19)
Traceback (most recent call last):
  File "scripts/extract_features.py", line 115, in <module>
    main(args)
  File "scripts/extract_features.py", line 109, in main
    feat_dset[i0:i1] = feats
TypeError: 'NoneType' object does not support item assignment

**Comment by RishikMani** [comment]
This also is happening for me and I cannot understand the logic behind this statement. Has anyone been able to solve this issue?

**Comment by RishikMani** [comment]
> This also is happening for me and I cannot understand the logic behind this statement. Has anyone been able to solve this issue?

I was able to resolve the issue. The reason was that I had far lesser number of images as compared to the batch_size. I had around 20 images with a bacth_size of 64. So unfortunately the statement

`if len(current_batch) == args.batch_size:` 

never returned **True** and thus the **h5py dataset never got created**. I updated my **batch_size** to 10 and I had it resolved.
