### ISSUE TITLE
IndexError!

### ISSUE THREAD

**Issue by JieyuZ2** [facebookresearch/clevr-iep#35]
Checking training accuracy ... 
Traceback (most recent call last):
  File "scripts/train_model.py", line 490, in <module>
    main(args)
  File "scripts/train_model.py", line 151, in main
    train_loop(args, train_loader, val_loader)
  File "scripts/train_model.py", line 269, in train_loop
    baseline_model, train_loader)
  File "scripts/train_model.py", line 460, in check_accuracy
    program_pred = program_generator.sample(Variable(questions[i:i+1].cuda(), volatile=True))
  File "/home/jiaruizou/research/clevr-iep/iep/models/seq2seq.py", line 154, in sample
    y.append(next_y[0, 0, 0])
IndexError: trying to index 3 dimensions of a 2 dimensional tensor

When I train the PG, it encounter this error...

**Comment by lixiangpengcs** [comment]
I met the same error as you. Do you find any solutions to solve this problem?

**Comment by louanesselma** [comment]
@JieyuZ2 
Hi,I got the same error,have you solve it?
