### ISSUE TITLE
  File "clevr-iep/iep/models/seq2seq.py", line 57, in get_dims     T_out = y.size(1) if y is not None else None

### ISSUE THREAD

**Issue by monajalal** [facebookresearch/clevr-iep#39]
```
[jalal@goku clevr-iep]$ python scripts/run_model.py   --program_generator models/CLEVR/program_generator_18k.pt   --execution_engine models/CLEVR/execution_engine_18k.pt   --image img/CLEVR_val_000013.png   --question "Does the small sphere have the same color as the cube left of the gray cube?"

Loading program generator from  models/CLEVR/program_generator_18k.pt
Loading execution engine from  models/CLEVR/execution_engine_18k.pt
Loading CNN for feature extraction
Downloading: "https://download.pytorch.org/models/resnet101-5d3b4d8f.pth" to /home/grad3/jalal/.torch/models/resnet101-5d3b4d8f.pth
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 178728960/178728960 [00:06<00:00, 28902620.29it/s]
scripts/run_model.py:133: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  img_var = Variable(torch.FloatTensor(img).type(dtype), volatile=True)
scripts/run_model.py:146: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  question_var = Variable(question_encoded, volatile=True)
Running the model

clevr-iep/iep/models/seq2seq.py:172: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  probs = F.softmax(logprobs.view(N, -1)) # Now N x V
Traceback (most recent call last):
  File "scripts/run_model.py", line 301, in <module>
    main(args)
  File "scripts/run_model.py", line 85, in main
    run_single_example(args, model)
  File "scripts/run_model.py", line 159, in run_single_example
    argmax=(args.sample_argmax == 1))
  File "/clevr-iep/iep/models/seq2seq.py", line 170, in reinforce_sample
    logprobs, h, c = self.decoder(encoded, cur_input, h0=h, c0=c)
  File "/clevr-iep/iep/models/seq2seq.py", line 92, in decoder
    V_in, V_out, D, H, L, N, T_in, T_out = self.get_dims(y=y)
  File "clevr-iep/iep/models/seq2seq.py", line 57, in get_dims
    T_out = y.size(1) if y is not None else None
RuntimeError: Dimension out of range (expected to be in range of [-1, 0], but got 1)
```

Can you please help how to fix this error?

**Comment by monajalal** [comment]
if you switch to Python 3.5 and Torch '0.1.11_5' problem fixes.
