### ISSUE TITLE
RuntimeError: CUDA error: out of memory for GTX 1080 Ti

### ISSUE THREAD

**Issue by monajalal** [facebookresearch/clevr-iep#40]
I have two GTX 1080 Ti but I get out of GPU memory error when I want to train. What GPU did you use and can I really not train it with GTX 1080 Ti? What is the minimum GPU specs I could run this code on?

```
[jalal@goku clevr-iep]$ python scripts/extract_features.py   --input_image_dir data/CLEVR_v1.0/images/train   --output_h5_file data/train_features.h5
('data/CLEVR_v1.0/images/train/CLEVR_train_000000.png', 0)
('data/CLEVR_v1.0/images/train/CLEVR_train_069999.png', 69999)
scripts/extract_features.py:57: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  image_batch = torch.autograd.Variable(image_batch, volatile=True)
Traceback (most recent call last):
  File "scripts/extract_features.py", line 114, in <module>
    main(args)
  File "scripts/extract_features.py", line 94, in main
    feats = run_batch(cur_batch, model)
  File "scripts/extract_features.py", line 59, in run_batch
    feats = model(image_batch)
  File "/scratch/sjn/anaconda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/scratch/sjn/anaconda/lib/python3.6/site-packages/torch/nn/modules/container.py", line 91, in forward
    input = module(input)
  File "/scratch/sjn/anaconda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/scratch/sjn/anaconda/lib/python3.6/site-packages/torch/nn/modules/container.py", line 91, in forward
    input = module(input)
  File "/scratch/sjn/anaconda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/scratch/sjn/anaconda/lib/python3.6/site-packages/torchvision-0.2.1-py3.6.egg/torchvision/models/resnet.py", line 84, in forward
  File "/scratch/sjn/anaconda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/scratch/sjn/anaconda/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 301, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: CUDA error: out of memory
[jalal@goku clevr-iep]$ nvidia-smi
Mon Sep 24 22:52:14 2018       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 410.48                 Driver Version: 410.48                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 108...  Off  | 00000000:05:00.0  On |                  N/A |
|  0%   25C    P0    62W / 250W |    445MiB / 11178MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX 108...  Off  | 00000000:06:00.0 Off |                  N/A |
|  0%   26C    P8    12W / 250W |      2MiB / 11178MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      2177      G   /usr/bin/X                                   309MiB |
|    0      3731      G   /usr/bin/gnome-shell                         125MiB |
|    0     10560      G   /usr/lib64/firefox/firefox                     2MiB |
|    0     13620      G   /usr/lib64/firefox/firefox                     2MiB |
|    0     14157      G   /usr/lib64/firefox/firefox                     2MiB |
+-----------------------------------------------------------------------------+
[jalal@goku clevr-iep]$ 
```

**Comment by monajalal** [comment]
if you switch to Python 3.5 and Torch '0.1.11_5' problem fixes.
